import{a as v,i as c,S as L}from"./assets/vendor-6e0bf343.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();async function h(e,r=1,n=15){const s="43748337-b5dbfef6f8220f61277bc8c0d",o=`https://pixabay.com/api/?${new URLSearchParams({key:s,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:n})}`;try{const a=await v.get(o);if(a.data.totalHits===0)throw new Error("There are no images matching your search query. Please try again!");return a.data}catch(a){throw console.error("Error fetching data:",a),a}}function m(e){const r=document.querySelector("#gallery"),n=e.map(s=>q(s));r.insertAdjacentHTML("beforeend",n.join(""))}function q(e){return`
    <a href="${e.largeImageURL}" class="image-card">
      <img src="${e.webformatURL}" alt="${e.tags}">
      <div class="details">
        <p>Likes: ${e.likes}</p>
        <p>Views: ${e.views}</p>
        <p>Comments: ${e.comments}</p>
        <p>Downloads: ${e.downloads}</p>
      </div>
    </a>
  `}const g=document.querySelector("#search-form"),d=document.querySelector("#search-input"),b=g.querySelector('button[type="submit"]'),P=document.querySelector("#gallery"),u=document.querySelector("#load-more"),y=document.getElementById("loader");let p=1,f="",i=0,l=0;d.addEventListener("input",()=>{const e=d.value.trim();b.disabled=e===""});g.addEventListener("submit",async e=>{e.preventDefault(),P.textContent="",f=d.value.trim(),p=1,i=0,l=0,u.style.display="none",y.style.display="block";try{const r=await h(f,p);i=r.totalHits,l=r.hits.length,i===0?c.error({message:"No images found for your search query. Please try again.",position:"topRight"}):(m(r.hits),w(),l<i&&(u.style.display="block"))}catch{c.error({message:"Failed to fetch data. Please try again later.",position:"topRight"})}finally{d.value="",b.disabled=!0,y.style.display="none"}});u.addEventListener("click",async()=>{p+=1,y.style.display="block";try{const e=await h(f,p);m(e.hits),w(),l+=e.hits.length,l>=i&&(u.style.display="none",c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),S()}catch{c.error({message:"Failed to fetch data. Please try again later.",position:"topRight"})}finally{y.style.display="none"}});function w(){new L("#gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}function S(){const{height:e}=document.querySelector(".image-card").getBoundingClientRect();console.log(e),window.scrollBy({top:Math.round(e)*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
